services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    volumes:
      - gestione-ordini-db:/var/lib/mysql
    networks:
      - gestione-ordini-network

  golang:
    build: .
    container_name: gestione-ordini-app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - gestione-ordini-network
    depends_on:
      - mysql

volumes:
  gestione-ordini-db:

networks:
  gestione-ordini-network:
