services:
  db:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./migrations/:/docker-entrypoint-initdb.d
    networks:
      - gestione-ordini-network

  app:
    image: cosmtrek/air
    container_name: gestione-ordini-app
    depends_on:
      - db
    restart: always
    working_dir: /app
    env_file:
      - .env
    environment:
      - GOFLAGS=-buildvcs=false
    volumes:
      - .:/app
    networks:
      - gestione-ordini-network

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mysql-data:

networks:
  gestione-ordini-network:
