services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/init_db/:/docker-entrypoint-initdb.d
    networks:
      - gestione-ordini-network

  golang:
    build: .
    container_name: gestione-ordini-app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - gestione-ordini-network
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  gestione-ordini-network:
