services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: go-app-container
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  app-network:
