services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/init_db/:/docker-entrypoint-initdb.d
    networks:
      - gestione-ordini-network

  golang:
    build: .
    container_name: gestione-ordini-app
    depends_on:
      - mysql
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - gestione-ordini-network
    ports:
      - "8080:8080"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    env_file:
      - .env
    environment:
      - PMA_HOST=${MYSQL_CONTAINER_NAME}
    networks:
      - gestione-ordini-network
    ports:
      - 8081:80

volumes:
  mysql-data:

networks:
  gestione-ordini-network:
