services:
  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./migrations/:/docker-entrypoint-initdb.d
    networks:
      - gestione-ordini-network

  tailwind:
    build: ./tailwind
    container_name: gestione-ordini-tailwind
    volumes:
      - .:/app

  golang:
    image: cosmtrek/air
    container_name: gestione-ordini-app
    depends_on:
      - mysql
    restart: always
    working_dir: /app
    env_file:
      - .env
    environment:
      - GOFLAGS=-buildvcs=false
    volumes:
      - .:/app
    networks:
      - gestione-ordini-network

volumes:
  mysql-data:

networks:
  gestione-ordini-network:
