services:
  db:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./migrations/:/docker-entrypoint-initdb.d
    networks:
      - gestione-ordini-network

  reverse-proxy:
    image: traefik:v3.1
    command:      
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gestione-ordini-network

  app:
    image: cosmtrek/air
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.routers.app.rule=Host(`gestione-ordini.enaiptesero.it`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
    depends_on:
      - db
    restart: always
    working_dir: /app
    env_file:
      - .env
    environment:
      - GOFLAGS=-buildvcs=false
    volumes:
      - .:/app
    networks:
      - gestione-ordini-network

volumes:
  mysql-data:

networks:
  gestione-ordini-network:
