services:
  db:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./migrations/:/docker-entrypoint-initdb.d
    networks:
      - gestione-ordini-network

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
    networks:
      - gestione-ordini-network

  app:
    image: cosmtrek/air
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
    restart: always
    working_dir: /app
    env_file:
      - .env
    environment:
      - GOFLAGS=-buildvcs=false
    volumes:
      - .:/app
    networks:
      - gestione-ordini-network

  tailwind:
    build: ./tailwind
    volumes:
      - .:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=${MYSQL_CONTAINER_NAME}
    networks:
      - gestione-ordini-network

volumes:
  mysql-data:
  letsencrypt:

networks:
  gestione-ordini-network:
